inicio:
    path:     /inicio
    defaults: { _controller: HomeBundle:Index:inicio }
    
index_video:
    path:     /index_video
    defaults: { _controller: HomeBundle:Index:indexVideo }
    methods: POST
    
pruebita:
    path:     /pruebita22
    defaults: { _controller: HomeBundle:Index:pruebita }

    
#index_video:
#    path:     /video
#    defaults: { _controller: HomeBundle:Procesar:video }
#    methods: POST
